### ISSUE TITLE
Support for reconciliation loops

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/operatorkit#2]
We have a general idea of operators that they should attempt to move actual state to desired state.

For example, a pingdom operator:
- watches for a pingdom resource in the cluster
- if the resource is created, creates an appropriate pingdom check
- if the resource is updated, updates the appropriate pingdom check
- if the resource is deleted, deletes the appropriate pingdom check

this approach (basically, using informers) works well for basic operators, in that they perform one action on informer action

more complicated operators may need to perform multiple actions on events.
for example, a cluster operator:
- when a resource is created, creates a set of vms, and some elb
if the vms are created successfully, and the elb not, then the operator should attempt to create the elb in the future. this doesn't really work with the informer based approach (maybe with relisting? but you need to ensure idempotency throughout)

there is a slightly higher idea of reconcilliation. my rough idea is that an operator should define some mapping between resource and underlying resource. e.g:
cluster == 3 vms, elb
and the framework then handles that these resources are present (or in the case of resource deletion, not present)

this would allow us to move the overall reconcilliation logic / resource management to one location, and make operators _much_ simpler, essentially being some function from resource to underlying resources.

**Comment by JosephSalisbury** [comment]
@rossf7 @xh3b4sd @asymmetric @nhlfr here's a big brain dump have at it

**Comment by xh3b4sd** [comment]
The described issue is different from the problem we talked about today IMO. The problem we discussed AFAIK was that operators often depend on multiple events to provide their actual business logic. E.g. our [aws-operator](https://github.com/giantswarm/aws-operator) has to listen to multiple different TPOs that provide information to be able to create a cluster. This separation causes us to have a better software design, but implies technical challenges this issue here is about. In the described case we have for instance multiple certificate TPOs, which have to be there to be able to create guest clusters on AWS. We experienced a case today in which only 3 out of 4 certificate TPOs have been available and the aws-operator timed out. IMO it should not time out, but do the reconciliation, track internal state, and process the actual event to apply business logic as soon as all requirements are met. So e.g. the current sequential reconciliation for a cluster creation has to be more dynamic and smart.

**Comment by asymmetric** [comment]
How would this "reconciliator" be able to handle all concrete resources we deal with, and still be generic/abstract? E.g. creating a LB vs a VPC - it needs specific knowledge about the different APIs.

So it would end up not being very abstract at all. We would have made the operators smaller at the cost of having shoved all the complexity for all the operators in one place.

Or did I just not understand what you mean?

**Comment by xh3b4sd** [comment]
This is the challenge software engineering wise. At the moment, I do not know. One possible way to find out would be to improve the reconciliation in the operators as they are right now. When we have what we want functionality wise we can start comparing the code and trying to draft some abstractions based on the code that already meets our requirements. So nobody has the right and perfect solution in mind at the moment. This is the engineering challenge. 

Talking off topic, we want to have small, logical operators, but in case of the AWS operator I do not see how the operator would be useful in case it would be smaller than a "create a guest cluster on EC2" operator.

**Comment by xh3b4sd** [comment]
The reconciler framework in operatorkit solves this.
